apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-entrypoint
  namespace: gateway-api
spec:
  gatewayClassName: nginx
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.local"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-local-tls
      allowedRoutes:
        namespaces:
          from: All    # 👈 allow HTTPRoutes in *any* namespace
